<?php

return [

    'companion' => [
        'maximum_message_characters' => (int) env('AI_COMPANION_MAX_MESSAGE_CHARACTERS', 8000),
        'maximum_pending_turns' => (int) env('AI_COMPANION_MAX_PENDING_TURNS', 4),
        'burst_window_milliseconds' => (int) env('AI_COMPANION_BURST_WINDOW_MILLISECONDS', 1200),
        'album_quiet_window_milliseconds' => (int) env('AI_COMPANION_ALBUM_QUIET_WINDOW_MILLISECONDS', 5000),
        'album_max_assembly_seconds' => (int) env('AI_COMPANION_ALBUM_MAX_ASSEMBLY_SECONDS', 30),
        'maximum_burst_messages' => (int) env('AI_COMPANION_MAX_BURST_MESSAGES', 4),
        'maximum_burst_characters' => (int) env('AI_COMPANION_MAX_BURST_CHARACTERS', 12000),
        'context_message_limit' => (int) env('AI_COMPANION_CONTEXT_MESSAGE_LIMIT', 24),
        'context_first_exchanges' => (int) env('AI_COMPANION_CONTEXT_FIRST_EXCHANGES', 2),
        'context_recent_exchanges' => (int) env('AI_COMPANION_CONTEXT_RECENT_EXCHANGES', 10),
        'context_max_characters' => (int) env('AI_COMPANION_CONTEXT_MAX_CHARACTERS', 12000),
        'context_max_input_characters' => (int) env('AI_COMPANION_CONTEXT_MAX_INPUT_CHARACTERS', 24000),
        'maximum_images_per_turn' => (int) env('AI_COMPANION_MAX_IMAGES_PER_TURN', 10),
        'maximum_image_bytes' => (int) env('AI_COMPANION_MAX_IMAGE_BYTES', 10_485_760),
        'maximum_image_total_bytes' => (int) env('AI_COMPANION_MAX_IMAGE_TOTAL_BYTES', 20_971_520),
        'maximum_image_pixels' => (int) env('AI_COMPANION_MAX_IMAGE_PIXELS', 25_000_000),
        'recent_image_turns' => (int) env('AI_COMPANION_RECENT_IMAGE_TURNS', 1),
        'maximum_export_messages' => (int) env('AI_COMPANION_MAX_EXPORT_MESSAGES', 2000),
        'history_page_size' => (int) env('AI_COMPANION_HISTORY_PAGE_SIZE', 30),
        'typing_heartbeat_seconds' => (int) env('AI_COMPANION_TYPING_HEARTBEAT_SECONDS', 4),
        'delivery_lease_seconds' => (int) env('AI_COMPANION_DELIVERY_LEASE_SECONDS', 60),
        'delivery_max_attempts' => (int) env('AI_COMPANION_DELIVERY_MAX_ATTEMPTS', 3),
        'delivery_retry_after_seconds' => (int) env('AI_COMPANION_DELIVERY_RETRY_AFTER_SECONDS', 5),
        'recent_image_max_age_minutes' => (int) env('AI_COMPANION_RECENT_IMAGE_MAX_AGE_MINUTES', 1440),
        'portal_rate_limit_per_minute' => (int) env('AI_COMPANION_PORTAL_RATE_LIMIT_PER_MINUTE', 12),
    ],

    'platform' => [
        'max_daily_spend_minor_units' => (int) env(
            'AI_PLATFORM_MAX_DAILY_SPEND_MINOR_UNITS',
            5000,
        ),
    ],

    /*
    |--------------------------------------------------------------------------
    | Default AI Provider Names
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the AI providers below should be the
    | default for AI operations when no explicit provider is provided
    | for the operation. This should be any provider defined below.
    |
    */

    'default' => 'openai',
    'default_for_images' => 'gemini',
    'default_for_audio' => 'openai',
    'default_for_transcription' => 'openai',
    'default_for_embeddings' => 'openai',
    'default_for_reranking' => 'cohere',

    'model_catalog' => [
        [
            'provider' => 'openai',
            'model' => 'gpt-5.6-terra',
            'display_name' => 'GPT-5.6 Terra',
            'family' => 'GPT-5.6',
            'summary' => 'Сбалансированный вариант для качества, скорости и стоимости.',
            'positioning' => 'Сбалансированная',
            'recommended' => true,
            'context_window_tokens' => 1_050_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '2.00',
                'output_price_per_million' => '12.00',
                'cache_read_input_price_per_million' => '0.20',
                'cache_write_input_price_per_million' => '2.50',
                'pricing_tiers' => [
                    [
                        'minimum_input_tokens' => 0,
                        'maximum_input_tokens' => 272_000,
                        'input_price_per_million' => '2.00',
                        'output_price_per_million' => '12.00',
                        'cache_read_input_price_per_million' => '0.20',
                        'cache_write_input_price_per_million' => '2.50',
                    ],
                    [
                        'minimum_input_tokens' => 272_001,
                        'maximum_input_tokens' => null,
                        'input_price_per_million' => '4.00',
                        'output_price_per_million' => '18.00',
                        'cache_read_input_price_per_million' => '0.40',
                        'cache_write_input_price_per_million' => '5.00',
                    ],
                ],
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://developers.openai.com/api/docs/models/gpt-5.6-terra',
            'pricing_as_of' => '2026-08-23',
        ],
        [
            'provider' => 'openai',
            'model' => 'gpt-5.6-sol',
            'display_name' => 'GPT-5.6 Sol',
            'family' => 'GPT-5.6',
            'summary' => 'Максимальное качество для сложных рассуждений и профессиональных задач.',
            'positioning' => 'Максимальное качество',
            'recommended' => false,
            'context_window_tokens' => 1_050_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '4.00',
                'output_price_per_million' => '20.00',
                'cache_read_input_price_per_million' => '0.40',
                'cache_write_input_price_per_million' => '5.00',
                'pricing_tiers' => [
                    [
                        'minimum_input_tokens' => 0,
                        'maximum_input_tokens' => 272_000,
                        'input_price_per_million' => '4.00',
                        'output_price_per_million' => '20.00',
                        'cache_read_input_price_per_million' => '0.40',
                        'cache_write_input_price_per_million' => '5.00',
                    ],
                    [
                        'minimum_input_tokens' => 272_001,
                        'maximum_input_tokens' => null,
                        'input_price_per_million' => '8.00',
                        'output_price_per_million' => '30.00',
                        'cache_read_input_price_per_million' => '0.80',
                        'cache_write_input_price_per_million' => '10.00',
                    ],
                ],
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://developers.openai.com/api/docs/models/gpt-5.6-sol',
            'pricing_as_of' => '2026-08-23',
        ],
        [
            'provider' => 'openai',
            'model' => 'gpt-5.6-luna',
            'display_name' => 'GPT-5.6 Luna',
            'family' => 'GPT-5.6',
            'summary' => 'Экономичный вариант для большого объёма обычных задач.',
            'positioning' => 'Экономичная / для большого объёма',
            'recommended' => false,
            'context_window_tokens' => 1_050_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.20',
                'output_price_per_million' => '1.20',
                'cache_read_input_price_per_million' => '0.02',
                'cache_write_input_price_per_million' => '0.25',
                'pricing_tiers' => [
                    [
                        'minimum_input_tokens' => 0,
                        'maximum_input_tokens' => 272_000,
                        'input_price_per_million' => '0.20',
                        'output_price_per_million' => '1.20',
                        'cache_read_input_price_per_million' => '0.02',
                        'cache_write_input_price_per_million' => '0.25',
                    ],
                    [
                        'minimum_input_tokens' => 272_001,
                        'maximum_input_tokens' => null,
                        'input_price_per_million' => '0.40',
                        'output_price_per_million' => '1.80',
                        'cache_read_input_price_per_million' => '0.04',
                        'cache_write_input_price_per_million' => '0.50',
                    ],
                ],
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://developers.openai.com/api/docs/models/gpt-5.6-luna',
            'pricing_as_of' => '2026-08-23',
        ],
        [
            'provider' => 'anthropic',
            'model' => 'claude-fable-5',
            'display_name' => 'Claude Fable 5',
            'family' => 'Claude 5',
            'summary' => 'Максимальное качество для сложных и длинных рабочих процессов.',
            'positioning' => 'Максимальное качество',
            'recommended' => false,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '10.00',
                'output_price_per_million' => '50.00',
                'cache_read_input_price_per_million' => '1.00',
                'cache_write_input_price_per_million' => '12.50',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://platform.claude.com/docs/en/about-claude/models/overview',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'anthropic',
            'model' => 'claude-opus-5',
            'display_name' => 'Claude Opus 5',
            'family' => 'Claude 5',
            'summary' => 'Сильная модель для агентных, корпоративных и сложных задач.',
            'positioning' => 'Очень высокое качество',
            'recommended' => false,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '5.00',
                'output_price_per_million' => '25.00',
                'cache_read_input_price_per_million' => '0.50',
                'cache_write_input_price_per_million' => '6.25',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://platform.claude.com/docs/en/about-claude/models/overview',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'anthropic',
            'model' => 'claude-sonnet-5',
            'display_name' => 'Claude Sonnet 5',
            'family' => 'Claude 5',
            'summary' => 'Баланс скорости, качества и стоимости для большинства сценариев.',
            'positioning' => 'Сбалансированная',
            'recommended' => true,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing_periods' => [
                [
                    'effective_from' => '2026-01-01 00:00:00',
                    'effective_until' => '2026-08-31 23:59:59',
                    'pricing' => [
                        'currency' => 'USD',
                        'input_price_per_million' => '2.00',
                        'output_price_per_million' => '10.00',
                        'cache_read_input_price_per_million' => '0.20',
                        'cache_write_input_price_per_million' => '2.50',
                        'fixed_request_cost_applicable' => false,
                        'unsupported_meters' => [],
                    ],
                ],
                [
                    'effective_from' => '2026-09-01 00:00:00',
                    'pricing' => [
                        'currency' => 'USD',
                        'input_price_per_million' => '3.00',
                        'output_price_per_million' => '15.00',
                        'cache_read_input_price_per_million' => '0.30',
                        'cache_write_input_price_per_million' => '3.75',
                        'fixed_request_cost_applicable' => false,
                        'unsupported_meters' => [],
                    ],
                ],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://platform.claude.com/docs/en/about-claude/pricing',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'anthropic',
            'model' => 'claude-haiku-4-5-20251001',
            'display_name' => 'Claude Haiku 4.5',
            'family' => 'Claude Haiku 4.5',
            'summary' => 'Самая быстрая и экономичная модель для большого потока задач.',
            'positioning' => 'Быстрая и экономичная',
            'recommended' => false,
            'context_window_tokens' => 200_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '1.00',
                'output_price_per_million' => '5.00',
                'cache_read_input_price_per_million' => '0.10',
                'cache_write_input_price_per_million' => '1.25',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://platform.claude.com/docs/en/about-claude/models/overview',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'gemini',
            'model' => 'gemini-3.7-flash',
            'display_name' => 'Gemini 3.7 Flash',
            'family' => 'Gemini 3',
            'summary' => 'Самая сильная Flash-модель для сложных многошаговых задач.',
            'positioning' => 'Максимальное качество среди быстрых моделей',
            'recommended' => true,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing_periods' => [
                [
                    'effective_until' => '2026-12-31 23:59:59',
                    'pricing' => [
                        'currency' => 'USD',
                        'input_price_per_million' => '0.75',
                        'output_price_per_million' => '3.75',
                        'cache_read_input_price_per_million' => '0.075',
                        'fixed_request_cost_applicable' => false,
                        'unsupported_meters' => [],
                    ],
                ],
                [
                    'effective_from' => '2027-01-01 00:00:00',
                    'pricing' => [
                        'currency' => 'USD',
                        'input_price_per_million' => '1.50',
                        'output_price_per_million' => '7.50',
                        'cache_read_input_price_per_million' => '0.15',
                        'fixed_request_cost_applicable' => false,
                        'unsupported_meters' => [],
                    ],
                ],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://ai.google.dev/gemini-api/docs/models',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'gemini',
            'model' => 'gemini-3.6-flash',
            'display_name' => 'Gemini 3.6 Flash',
            'family' => 'Gemini 3',
            'summary' => 'Сбалансированная мультимодальная модель для повседневных задач.',
            'positioning' => 'Сбалансированная',
            'recommended' => false,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing_periods' => [
                [
                    'effective_until' => '2026-12-31 23:59:59',
                    'pricing' => [
                        'currency' => 'USD',
                        'input_price_per_million' => '0.75',
                        'output_price_per_million' => '3.75',
                        'cache_read_input_price_per_million' => '0.075',
                        'fixed_request_cost_applicable' => false,
                        'unsupported_meters' => [],
                    ],
                ],
                [
                    'effective_from' => '2027-01-01 00:00:00',
                    'pricing' => [
                        'currency' => 'USD',
                        'input_price_per_million' => '1.50',
                        'output_price_per_million' => '7.50',
                        'cache_read_input_price_per_million' => '0.15',
                        'fixed_request_cost_applicable' => false,
                        'unsupported_meters' => [],
                    ],
                ],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://ai.google.dev/gemini-api/docs/models',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'gemini',
            'model' => 'gemini-3.5-flash',
            'display_name' => 'Gemini 3.5 Flash',
            'family' => 'Gemini 3',
            'summary' => 'Проверенный быстрый вариант для обычных и массовых задач.',
            'positioning' => 'Экономичная',
            'recommended' => false,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '1.50',
                'output_price_per_million' => '9.00',
                'cache_read_input_price_per_million' => '0.15',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://ai.google.dev/gemini-api/docs/models',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'gemini',
            'model' => 'gemini-3.5-flash-lite',
            'display_name' => 'Gemini 3.5 Flash-Lite',
            'family' => 'Gemini 3.5',
            'summary' => 'Экономичная модель для большого объёма простых задач.',
            'positioning' => 'Экономичная / для большого объёма',
            'recommended' => false,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.30',
                'output_price_per_million' => '2.50',
                'cache_read_input_price_per_million' => '0.03',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://ai.google.dev/gemini-api/docs/models',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'gemini',
            'model' => 'gemini-3.1-flash-lite',
            'display_name' => 'Gemini 3.1 Flash-Lite',
            'family' => 'Gemini 3.1',
            'summary' => 'Очень экономичный вариант для высокочастотных операций.',
            'positioning' => 'Самая экономичная',
            'recommended' => false,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input', 'document_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.25',
                'output_price_per_million' => '1.50',
                'cache_read_input_price_per_million' => '0.025',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'deprecated',
            'catalog_source' => 'https://ai.google.dev/gemini-api/docs/models',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'deepseek',
            'model' => 'deepseek-v4-pro',
            'display_name' => 'DeepSeek V4 Pro',
            'family' => 'DeepSeek V4',
            'summary' => 'Максимальное качество DeepSeek для сложных текстовых задач.',
            'positioning' => 'Максимальное качество',
            'recommended' => true,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => [],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.435',
                'output_price_per_million' => '0.87',
                'cache_read_input_price_per_million' => '0.003625',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://api-docs.deepseek.com/quick_start/pricing/',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'deepseek',
            'model' => 'deepseek-v4-flash',
            'display_name' => 'DeepSeek V4 Flash',
            'family' => 'DeepSeek V4',
            'summary' => 'Быстрый и экономичный DeepSeek для большого объёма текста.',
            'positioning' => 'Экономичная / для большого объёма',
            'recommended' => false,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => [],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.14',
                'output_price_per_million' => '0.28',
                'cache_read_input_price_per_million' => '0.0028',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://api-docs.deepseek.com/quick_start/pricing/',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'mistral',
            'model' => 'mistral-medium-3-5',
            'display_name' => 'Mistral Medium 3.5',
            'family' => 'Mistral 3',
            'summary' => 'Сильная мультимодальная модель для агентных и кодовых задач.',
            'positioning' => 'Максимальное качество',
            'recommended' => true,
            'context_window_tokens' => 256_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '1.50',
                'output_price_per_million' => '7.50',
                'cache_read_input_price_per_million' => '0.15',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://docs.mistral.ai/models/mistral-medium-3-5-26-04',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'mistral',
            'model' => 'mistral-large-2512',
            'display_name' => 'Mistral Large 3',
            'family' => 'Mistral 3',
            'summary' => 'Открытая general-purpose модель с мультимодальным входом.',
            'positioning' => 'Сбалансированная',
            'recommended' => false,
            'context_window_tokens' => 256_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.50',
                'output_price_per_million' => '1.50',
                'cache_read_input_price_per_million' => '0.05',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://docs.mistral.ai/models/mistral-large-3-25-12',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'mistral',
            'model' => 'mistral-small-2603',
            'display_name' => 'Mistral Small 4',
            'family' => 'Mistral 4',
            'summary' => 'Быстрый гибридный вариант для текста, рассуждений и кода.',
            'positioning' => 'Экономичная',
            'recommended' => false,
            'context_window_tokens' => 256_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.15',
                'output_price_per_million' => '0.60',
                'cache_read_input_price_per_million' => '0.015',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://docs.mistral.ai/models/mistral-small-4-0-26-03',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'mistral',
            'model' => 'ministral-14b-2512',
            'display_name' => 'Ministral 3 14B',
            'family' => 'Ministral 3',
            'summary' => 'Компактная модель с хорошим качеством для локальных и быстрых задач.',
            'positioning' => 'Быстрая и экономичная',
            'recommended' => false,
            'context_window_tokens' => 256_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.20',
                'output_price_per_million' => '0.20',
                'cache_read_input_price_per_million' => '0.02',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://docs.mistral.ai/models/ministral-3-14b-25-12',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'mistral',
            'model' => 'ministral-8b-2512',
            'display_name' => 'Ministral 3 8B',
            'family' => 'Ministral 3',
            'summary' => 'Самый экономичный вариант Mistral для быстрого потока задач.',
            'positioning' => 'Самая экономичная',
            'recommended' => false,
            'context_window_tokens' => 256_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.15',
                'output_price_per_million' => '0.15',
                'cache_read_input_price_per_million' => '0.015',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://docs.mistral.ai/models/ministral-3-8b-25-12',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'groq',
            'model' => 'openai/gpt-oss-120b',
            'display_name' => 'GPT OSS 120B на Groq',
            'family' => 'GPT OSS',
            'summary' => 'Производительная открытая модель для сложных текстовых задач.',
            'positioning' => 'Максимальное качество',
            'recommended' => true,
            'context_window_tokens' => 131_072,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => [],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.15',
                'output_price_per_million' => '0.60',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://console.groq.com/docs/models',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'groq',
            'model' => 'openai/gpt-oss-20b',
            'display_name' => 'GPT OSS 20B на Groq',
            'family' => 'GPT OSS',
            'summary' => 'Быстрый экономичный вариант для большого объёма текста.',
            'positioning' => 'Быстрая и экономичная',
            'recommended' => false,
            'context_window_tokens' => 131_072,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => [],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '0.075',
                'output_price_per_million' => '0.30',
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://console.groq.com/docs/models',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'xai',
            'model' => 'grok-4.6',
            'display_name' => 'Grok 4.6',
            'family' => 'Grok 4',
            'summary' => 'Флагманская модель для кода, агентных и рабочих задач.',
            'positioning' => 'Максимальное качество',
            'recommended' => true,
            'context_window_tokens' => 500_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '2.00',
                'output_price_per_million' => '6.00',
                'cache_read_input_price_per_million' => '0.50',
                'pricing_tiers' => [
                    [
                        'minimum_input_tokens' => 0,
                        'maximum_input_tokens' => 199_999,
                        'input_price_per_million' => '2.00',
                        'output_price_per_million' => '6.00',
                        'cache_read_input_price_per_million' => '0.50',
                    ],
                    [
                        'minimum_input_tokens' => 200_000,
                        'maximum_input_tokens' => null,
                        'input_price_per_million' => '4.00',
                        'output_price_per_million' => '12.00',
                        'cache_read_input_price_per_million' => '1.00',
                    ],
                ],
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://docs.x.ai/developers/models',
            'pricing_as_of' => '2026-08-22',
        ],
        [
            'provider' => 'xai',
            'model' => 'grok-4.3',
            'display_name' => 'Grok 4.3',
            'family' => 'Grok 4',
            'summary' => 'Быстрая модель с сильным следованием инструкциям и инструментами.',
            'positioning' => 'Сбалансированная',
            'recommended' => false,
            'context_window_tokens' => 1_000_000,
            'supported_capabilities' => ['text_generation', 'structured_output'],
            'modalities' => ['image_input'],
            'pricing' => [
                'currency' => 'USD',
                'input_price_per_million' => '1.25',
                'output_price_per_million' => '2.50',
                'cache_read_input_price_per_million' => '0.20',
                'pricing_tiers' => [
                    [
                        'minimum_input_tokens' => 0,
                        'maximum_input_tokens' => 199_999,
                        'input_price_per_million' => '1.25',
                        'output_price_per_million' => '2.50',
                        'cache_read_input_price_per_million' => '0.20',
                    ],
                    [
                        'minimum_input_tokens' => 200_000,
                        'maximum_input_tokens' => null,
                        'input_price_per_million' => '2.50',
                        'output_price_per_million' => '5.00',
                        'cache_read_input_price_per_million' => '0.40',
                    ],
                ],
                'fixed_request_cost_applicable' => false,
                'unsupported_meters' => [],
            ],
            'lifecycle' => 'active',
            'catalog_source' => 'https://docs.x.ai/developers/models/grok-4.3',
            'pricing_as_of' => '2026-08-22',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Caching
    |--------------------------------------------------------------------------
    |
    | Below you may configure caching strategies for AI related operations
    | such as embedding generation. You are free to adjust these values
    | based on your application's available caching stores and needs.
    |
    */

    'caching' => [
        'embeddings' => [
            'cache' => false,
            'store' => env('CACHE_STORE', 'database'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | AI Providers
    |--------------------------------------------------------------------------
    |
    | Below are each of your AI providers defined for this application. Each
    | represents an AI provider and API key combination which can be used
    | to perform tasks like text, image, and audio creation via agents.
    |
    */

    'providers' => [
        'anthropic' => [
            'driver' => 'anthropic',
            'key' => env('ANTHROPIC_API_KEY'),
            'url' => env('ANTHROPIC_URL', 'https://api.anthropic.com/v1'),
        ],

        'azure' => [
            'driver' => 'azure',
            'key' => env('AZURE_OPENAI_API_KEY'),
            'url' => env('AZURE_OPENAI_URL'),
            'api_version' => env('AZURE_OPENAI_API_VERSION', '2025-04-01-preview'),
            'deployment' => env('AZURE_OPENAI_DEPLOYMENT', 'gpt-4o'),
            'embedding_deployment' => env('AZURE_OPENAI_EMBEDDING_DEPLOYMENT', 'text-embedding-3-small'),
            'image_deployment' => env('AZURE_OPENAI_IMAGE_DEPLOYMENT', 'gpt-image-1'),
            'store' => env('AZURE_OPENAI_STORE', true),
        ],

        'bedrock' => [
            'driver' => 'bedrock',
            'region' => env('AWS_BEDROCK_REGION', 'us-east-1'),
            'key' => env('AWS_BEARER_TOKEN_BEDROCK'),
            'access_key_id' => env('AWS_ACCESS_KEY_ID'),
            'secret_access_key' => env('AWS_SECRET_ACCESS_KEY'),
            'session_token' => env('AWS_SESSION_TOKEN'),
            'use_default_credential_provider' => env('AWS_USE_DEFAULT_CREDENTIALS', true),
            'assume_role' => [
                'arn' => env('AWS_BEDROCK_ASSUME_ROLE_ARN'),
                'session_name' => env('AWS_BEDROCK_ASSUME_ROLE_SESSION_NAME'),
                'duration_seconds' => env('AWS_BEDROCK_ASSUME_ROLE_DURATION_SECONDS'),
                'external_id' => env('AWS_BEDROCK_ASSUME_ROLE_EXTERNAL_ID'),
            ],
        ],

        'cohere' => [
            'driver' => 'cohere',
            'key' => env('COHERE_API_KEY'),
        ],

        'deepseek' => [
            'driver' => 'deepseek',
            'key' => env('DEEPSEEK_API_KEY'),
        ],

        'eleven' => [
            'driver' => 'eleven',
            'key' => env('ELEVENLABS_API_KEY'),
        ],

        'gemini' => [
            'driver' => 'gemini',
            'key' => env('GEMINI_API_KEY'),
            'url' => env('GEMINI_URL', 'https://generativelanguage.googleapis.com/v1beta/'),
        ],

        'groq' => [
            'driver' => 'groq',
            'key' => env('GROQ_API_KEY'),
        ],

        'jina' => [
            'driver' => 'jina',
            'key' => env('JINA_API_KEY'),
        ],

        'mistral' => [
            'driver' => 'mistral',
            'key' => env('MISTRAL_API_KEY'),
        ],

        'ollama' => [
            'driver' => 'ollama',
            'key' => env('OLLAMA_API_KEY', ''),
            'url' => env('OLLAMA_URL', 'http://localhost:11434'),
        ],

        'openai' => [
            'driver' => 'openai',
            'key' => env('OPENAI_API_KEY'),
            'url' => env('OPENAI_URL', 'https://api.openai.com/v1'),
            'store' => env('OPENAI_STORE', true),
        ],

        'openai-compatible' => [
            'driver' => 'openai-compatible',
            'url' => env('OPENAI_COMPATIBLE_URL'),
            'key' => env('OPENAI_COMPATIBLE_API_KEY'),
        ],

        'openrouter' => [
            'driver' => 'openrouter',
            'key' => env('OPENROUTER_API_KEY'),
        ],

        'voyageai' => [
            'driver' => 'voyageai',
            'key' => env('VOYAGEAI_API_KEY'),
        ],

        'xai' => [
            'driver' => 'xai',
            'key' => env('XAI_API_KEY'),
        ],
    ],

];
