<?php

return [
    'embedding' => [
        'provider' => env('RAG_EMBEDDING_PROVIDER', 'openai'),
        'model' => env('RAG_EMBEDDING_MODEL', 'text-embedding-3-small'),
        'dimensions' => (int) env('RAG_EMBEDDING_DIMENSIONS', 1536),
        'configuration_version' => env('RAG_EMBEDDING_CONFIGURATION_VERSION', 'v1'),
        'catalog_source' => 'https://developers.openai.com/api/docs/models/text-embedding-3-small',
        'verified_as_of' => '2026-08-22',
        'timeout_seconds' => (int) env('RAG_EMBEDDING_TIMEOUT_SECONDS', 30),
        'pricing' => [
            'provider' => env('RAG_EMBEDDING_PRICING_PROVIDER', env('RAG_EMBEDDING_PROVIDER', 'openai')),
            'model' => env('RAG_EMBEDDING_PRICING_MODEL', env('RAG_EMBEDDING_MODEL', 'text-embedding-3-small')),
            'configuration_version' => env('RAG_EMBEDDING_PRICING_CONFIGURATION_VERSION', env('RAG_EMBEDDING_CONFIGURATION_VERSION', 'v1')),
            'currency' => env('RAG_EMBEDDING_PRICING_CURRENCY', 'USD'),
            'catalog_source' => 'https://developers.openai.com/api/docs/models/text-embedding-3-small',
            'pricing_as_of' => '2026-08-22',
            'input_rate_per_million_units' => env('RAG_EMBEDDING_INPUT_RATE_PER_MILLION_UNITS'),
            'input_price_per_million' => env('RAG_EMBEDDING_INPUT_PRICE_PER_MILLION'),
            'input_cost_per_million_minor_units' => env('RAG_EMBEDDING_INPUT_COST_PER_MILLION_MINOR_UNITS'),
            'zero_cost_local' => (bool) env('RAG_EMBEDDING_ZERO_COST_LOCAL', false),
        ],
    ],
    'model_catalog' => [
        'embedding' => [
            [
                'provider' => 'openai',
                'model' => 'text-embedding-3-small',
                'display_name' => 'OpenAI Embeddings Small',
                'summary' => 'Быстрая мультиязычная индексация для большинства баз знаний.',
                'positioning' => 'Экономичная',
                'dimensions' => 1536,
                'context_window_tokens' => 8191,
                'input_price_per_million' => '0.02',
                'currency' => 'USD',
                'lifecycle' => 'active',
                'recommended' => true,
                'catalog_source' => 'https://developers.openai.com/api/docs/models/text-embedding-3-small',
                'pricing_as_of' => '2026-08-22',
            ],
            [
                'provider' => 'openai',
                'model' => 'text-embedding-3-large',
                'display_name' => 'OpenAI Embeddings Large',
                'summary' => 'Максимальное качество OpenAI для сложного мультиязычного поиска.',
                'positioning' => 'Максимальное качество',
                'dimensions' => 3072,
                'context_window_tokens' => 8191,
                'input_price_per_million' => '0.13',
                'currency' => 'USD',
                'lifecycle' => 'active',
                'catalog_source' => 'https://developers.openai.com/api/docs/models/text-embedding-3-large',
                'pricing_as_of' => '2026-08-22',
            ],
            [
                'provider' => 'cohere',
                'model' => 'embed-v4.0',
                'display_name' => 'Cohere Embed v4',
                'summary' => 'Мультиязычная индексация текста и содержимого изображений/PDF.',
                'positioning' => 'Сбалансированная',
                'dimensions' => 1536,
                'context_window_tokens' => 128000,
                'lifecycle' => 'active',
                'catalog_source' => 'https://docs.cohere.com/v2/docs/models',
                'pricing_as_of' => '2026-08-22',
            ],
            [
                'provider' => 'jina',
                'model' => 'jina-embeddings-v5-text-small',
                'display_name' => 'Jina Embeddings v5 Text Small',
                'summary' => 'Мультиязычная текстовая индексация с task-адаптерами.',
                'positioning' => 'Сбалансированная',
                'dimensions' => 1024,
                'context_window_tokens' => 32000,
                'lifecycle' => 'active',
                'catalog_source' => 'https://jina.ai/models/jina-embeddings-v5-text-small/',
                'pricing_as_of' => '2026-08-22',
            ],
            [
                'provider' => 'jina',
                'model' => 'jina-embeddings-v5-text-nano',
                'display_name' => 'Jina Embeddings v5 Text Nano',
                'summary' => 'Компактная мультиязычная индексация для высокой пропускной способности.',
                'positioning' => 'Экономичная / высокая пропускная способность',
                'dimensions' => 768,
                'context_window_tokens' => 8192,
                'lifecycle' => 'active',
                'catalog_source' => 'https://jina.ai/models/',
                'pricing_as_of' => '2026-08-22',
            ],
            [
                'provider' => 'voyageai',
                'model' => 'voyage-4-large',
                'display_name' => 'Voyage 4 Large',
                'summary' => 'Максимальное качество мультиязычного поиска и индексации.',
                'positioning' => 'Максимальное качество',
                'dimensions' => 1024,
                'context_window_tokens' => 32000,
                'input_price_per_million' => '0.12',
                'currency' => 'USD',
                'lifecycle' => 'active',
                'recommended' => false,
                'catalog_source' => 'https://docs.voyageai.com/docs/embeddings',
                'pricing_as_of' => '2026-08-23',
            ],
            [
                'provider' => 'voyageai',
                'model' => 'voyage-4',
                'display_name' => 'Voyage 4',
                'summary' => 'Сбалансированная модель для общего мультиязычного RAG-поиска.',
                'positioning' => 'Сбалансированная',
                'dimensions' => 1024,
                'context_window_tokens' => 32000,
                'input_price_per_million' => '0.06',
                'currency' => 'USD',
                'lifecycle' => 'active',
                'recommended' => true,
                'catalog_source' => 'https://docs.voyageai.com/docs/embeddings',
                'pricing_as_of' => '2026-08-23',
            ],
            [
                'provider' => 'voyageai',
                'model' => 'voyage-4-lite',
                'display_name' => 'Voyage 4 Lite',
                'summary' => 'Экономичная модель для большого объёма индексации и низкой задержки.',
                'positioning' => 'Экономичная / высокая пропускная способность',
                'dimensions' => 1024,
                'context_window_tokens' => 32000,
                'input_price_per_million' => '0.02',
                'currency' => 'USD',
                'lifecycle' => 'active',
                'recommended' => false,
                'catalog_source' => 'https://docs.voyageai.com/docs/embeddings',
                'pricing_as_of' => '2026-08-23',
            ],
        ],
        'reranking' => [
            [
                'provider' => 'cohere',
                'model' => 'rerank-v4.0-pro',
                'display_name' => 'Cohere Rerank v4 Pro',
                'summary' => 'Максимальное качество мультиязычного reranking для сложных запросов.',
                'positioning' => 'Максимальное качество',
                'context_window_tokens' => 32000,
                'billing_meter' => 'search_units',
                'lifecycle' => 'active',
                'catalog_source' => 'https://docs.cohere.com/v2/docs/models',
                'pricing_as_of' => '2026-08-22',
            ],
            [
                'provider' => 'cohere',
                'model' => 'rerank-v4.0-fast',
                'display_name' => 'Cohere Rerank v4 Fast',
                'summary' => 'Быстрый reranking для большого числа поисковых запросов.',
                'positioning' => 'Быстрая / высокая пропускная способность',
                'context_window_tokens' => 32000,
                'billing_meter' => 'search_units',
                'lifecycle' => 'active',
                'catalog_source' => 'https://docs.cohere.com/v2/docs/models',
                'pricing_as_of' => '2026-08-22',
            ],
            [
                'provider' => 'jina',
                'model' => 'jina-reranker-v3.5',
                'display_name' => 'Jina Reranker v3.5',
                'summary' => 'Мультиязычный listwise reranking для документов и структурированных данных.',
                'positioning' => 'Сбалансированная',
                'context_window_tokens' => 131000,
                'billing_meter' => 'provider_defined',
                'lifecycle' => 'active',
                'catalog_source' => 'https://jina.ai/models/jina-reranker-v3.5/',
                'pricing_as_of' => '2026-08-22',
            ],
            [
                'provider' => 'voyageai',
                'model' => 'rerank-2.5',
                'display_name' => 'Voyage Rerank 2.5',
                'summary' => 'Максимальное качество reranking для мультиязычного поиска.',
                'positioning' => 'Максимальное качество',
                'context_window_tokens' => 32000,
                'input_price_per_million' => '0.05',
                'currency' => 'USD',
                'billing_meter' => 'processed_tokens',
                'lifecycle' => 'active',
                'catalog_source' => 'https://docs.voyageai.com/docs/reranker',
                'pricing_as_of' => '2026-08-23',
            ],
            [
                'provider' => 'voyageai',
                'model' => 'rerank-2.5-lite',
                'display_name' => 'Voyage Rerank 2.5 Lite',
                'summary' => 'Быстрый и экономичный reranking для большого числа результатов.',
                'positioning' => 'Экономичная / высокая пропускная способность',
                'context_window_tokens' => 32000,
                'input_price_per_million' => '0.02',
                'currency' => 'USD',
                'billing_meter' => 'processed_tokens',
                'lifecycle' => 'active',
                'catalog_source' => 'https://docs.voyageai.com/docs/reranker',
                'pricing_as_of' => '2026-08-23',
            ],
        ],
    ],
    'chunking' => [
        'strategy' => 'normalized-character-window',
        'version' => 'v1',
        'target_characters' => 1200,
        'maximum_characters' => 1600,
        'overlap_characters' => 160,
    ],
    'retrieval' => [
        'default_top_k' => 5,
        'maximum_top_k' => 20,
        'minimum_similarity' => 0.0,
    ],
    'processing_stale_after_seconds' => 1800,
    'uploads' => [
        'disk' => 'private',
        'maximum_kilobytes' => 2048,
        'maximum_extracted_characters' => 500000,
        'allowed_mime_types' => ['text/plain', 'text/markdown'],
        'allowed_extensions' => ['txt', 'md', 'markdown'],
    ],
];
